### ISSUE TITLE
trump 2024

### ISSUE THREAD

**Issue by ghost** [SpeakerZ-01/minecraft-3ds-options-binary-remover#3]
![image](https://github.com/user-attachments/assets/e051c186-ddc6-469c-91f5-26061bfa5673)

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/75e5e629-1140-4edf-a11c-c19a956b67a9)

**Comment by SpeakerZ-01** [comment]
why is harass me

**Comment by ghost** [comment]
what?

**Comment by SeveringHams** [comment]
no can ingles either?

**Comment by ghost** [comment]
oh shit this is a live chat lol

**Comment by SeveringHams** [comment]
me so smart

**Comment by SpeakerZ-01** [comment]
is live chat yes

**Comment by SeveringHams** [comment]
very so much good

**Comment by ghost** [comment]
ingriush

**Comment by SpeakerZ-01** [comment]
i try is my english

**Comment by SeveringHams** [comment]
unistore is safe good yes

**Comment by ghost** [comment]
no unistore is virus

**Comment by SpeakerZ-01** [comment]
are not banned you?

**Comment by SeveringHams** [comment]
you try very good very good

**Comment by SpeakerZ-01** [comment]
why is he say banned are you

**Comment by ghost** [comment]
i no barned

**Comment by SeveringHams** [comment]
no barning here?

**Comment by SpeakerZ-01** [comment]
barning like animal

**Comment by ghost** [comment]
yes

**Comment by SeveringHams** [comment]
yes barning like animal but no barmning here

**Comment by SpeakerZ-01** [comment]
or burning like jews

**Comment by ghost** [comment]
![uhh-patrick-star](https://github.com/user-attachments/assets/5c4e85ae-1d9a-4a9c-8824-055fb07801af)

**Comment by SeveringHams** [comment]
HUH?

**Comment by ghost** [comment]
what skibidi, th. e

**Comment by SeveringHams** [comment]
why jews burning?

**Comment by SpeakerZ-01** [comment]
is ok have good time in hell place yes

**Comment by ghost** [comment]
dude im serious you cannot mod if you cant speak

**Comment by ghost** [comment]
let me say this in a way you can understand

**Comment by SpeakerZ-01** [comment]
is you banned?

**Comment by SeveringHams** [comment]
no you are

**Comment by ghost** [comment]
speak enrighjs no modding

**Comment by ghost** [comment]
https://github.com/user-attachments/assets/df4fd1a9-ab8b-4539-9b0e-460aaa45053b
